spring:
  r2dbc:
    url: ${R2DBC_DATASOURCE_URL:r2dbc:postgresql://localhost:5432/generative_content_service}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    initialization-mode: ${DATA_INITIALIZATION_MODE:never}
    pool:
      enabled: ${DB_POOL_ENABLED:true}
      initial-size: ${DB_POOL_INITIAL_SIZE:10}
      max-size: ${DB_POOL_MAX_SIZE:50}
      max-idle-time: ${DB_POOL_IDLE_TIMEOUT_DURATION:2m}
  jpa:
    hibernate:
      ddl-auto: none
  webflux:
    base-path: /generative-content-service
  codec:
    max-in-memory-size: ${SPRING_CODE_MAX_IN_MEMORY_SIZE:10MB}

server:
  port: 8085

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:4005}
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles:
        http:
          client:
            requests: ${CLIENT_REQUEST_PERCENTILES:.5D,.90D,.95D,.99D}
          server:
            requests: ${SERVER_REQUEST_PERCENTILES:.5D,.90D,.95D,.99D}

# netty configs
netty-http-client:
  default:
    max-connections: ${NETTY_HTTP_CLIENT_DEFAULT_MAX_CONNECTION:100}
    max-connection-idle-time-in-ms: ${NETTY_HTTP_CLIENT_DEFAULT_MAX_CONNECTION_IDLE_TIME_MS:10000}
    evict-interval-time-in-ms: ${NETTY_HTTP_CLIENT_DEFAULT_EVICT_INTERVAL_IDLE_TIME_MS:2000}

chat-gpt-client:
  responseTimeoutInMs: 1000
  connectionTimeoutInMs: 1000

# To Access chat gpt APIs
chat-gpt:
  default:
    token: ${CHAT_GPT_TOKEN:testToken}
    baseUrl: http://localhost:8097/
