spring:
  main:
    web-application-type: NONE
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/generative_content_service
    username: postgres
    password: postgres
    initialization-mode: ${DATA_INITIALIZATION_MODE:never}
    hikari:
      idle-timeout: ${DB_POOL_IDLE_TIMEOUT_IN_MS:30000}
      maximum-pool-size: ${DB_POOL_MAX_SIZE:2}
      minimum-idle: ${DB_POOL_MIN_IDLE:1}
  liquibase:
    url: jdbc:postgresql://localhost:5432/generative_content_service
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/liquibase-changelog.yaml
  jpa:
    hibernate:
      ddl-auto: none
